$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            item:1
        },
        600:{
            item:2
        },
        1000:{
            item:3
        }
    }
})